# CineMatch AI - Movie Recommendation System

## Project Overview

CineMatch AI is a content-based movie recommendation system that suggests similar movies based on user-selected movies.

The main goal of this project is to build an end-to-end machine learning application that combines data preprocessing, natural language processing, similarity-based recommendation techniques, and a user-friendly web interface.

In this project, movie metadata such as genres, keywords, cast, crew, and descriptions are analyzed to understand the characteristics of each movie. The system uses TF-IDF vectorization and cosine similarity to find and recommend movies with similar content.

## Objectives

The main objectives of this project are:

- Understand and preprocess movie metadata.
- Apply feature engineering techniques to extract meaningful information.
- Build a content-based recommendation engine using NLP techniques.
- Calculate similarity between movies using machine learning algorithms.
- Save the trained recommendation model for future use.
- Deploy the model using Streamlit for an interactive user experience.

## Technologies Used

- **Programming Language:** Python
- **Data Processing:** Pandas, NumPy
- **Machine Learning:** Scikit-Learn
- **NLP Technique:** TF-IDF Vectorization
- **Similarity Algorithm:** Cosine Similarity
- **Model Storage:** Pickle
- **Application Development:** Streamlit

## Dataset

The project uses the TMDB 5000 Movie Dataset, which contains movie information including titles, genres, keywords, cast, crew, and descriptions.

This dataset helps in creating meaningful movie representations for generating recommendations.

## Project Workflow

Dataset Collection  
↓  
Data Cleaning & Preprocessing  
↓  
Feature Engineering  
↓  
Text Vectorization using TF-IDF  
↓  
Similarity Calculation using Cosine Similarity  
↓  
Recommendation Engine Development  
↓  
Model Saving  
↓  
Streamlit Web Application

## Expected Outcome

The final application allows users to select a movie and receive a list of similar movie recommendations through an interactive web interface.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

## Dataset Loading

In this section, we load the TMDB 5000 Movie Dataset and inspect its structure.

The dataset contains movie metadata and credits information, which will be combined to create a complete dataset for building our recommendation system.

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/CineMatch-AI/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/drive/MyDrive/CineMatch-AI/tmdb_5000_credits.csv')

In [ ]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies.shape

(4803, 20)

In [ ]:
credits.shape

(4803, 4)

## Data Cleaning and Preprocessing

Before building the recommendation model, the dataset needs to be cleaned and prepared.

This step includes merging datasets, selecting relevant features, handling missing values, and removing duplicate records to improve recommendation accuracy.

In [ ]:
movies = movies.merge(credits, on='title')

In [ ]:
movies.shape

(4809, 23)

In [ ]:
movies = movies[['movie_id',
                 'title',
                 'overview',
                 'genres',
                 'keywords',
                 'cast',
                 'crew']]

## Feature Engineering

In this section, we will transform raw movie information into meaningful features for our recommendation system.

Different attributes such as genres, keywords, cast, crew, and overview will be combined to create a single text-based feature that represents each movie.

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
import ast

In [ ]:
def convert(obj):
    List = []
    for i in ast.literal_eval(obj):
        List.append(i['name'])
    return List

In [ ]:
movies['genres'] = movies['genres'].apply(convert)

In [ ]:
movies['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)

In [ ]:
movies['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

**For Top 3 cast**

In [ ]:
def convert_cast(obj):
    List = []
    counter = 0

    for i in ast.literal_eval(obj):
        if counter < 3:
            List.append(i['name'])
            counter += 1
        else:
            break

    return List

In [ ]:
movies['cast'] = movies['cast'].apply(convert_cast)
movies['cast'].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

**For Director**

In [ ]:
def fetch_director(obj):
    List = []

    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            List.append(i['name'])
            break

    return List

In [ ]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies['crew'].head()

0        [James Cameron]
1       [Gore Verbinski]
2           [Sam Mendes]
3    [Christopher Nolan]
4       [Andrew Stanton]
Name: crew, dtype: object

In [ ]:
movies.rename(columns={'crew':'director'}, inplace=True)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [ ]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

AttributeError: 'float' object has no attribute 'split'

In [ ]:
movies['overview'].isnull().sum()

np.int64(3)

In [ ]:
movies.dropna(subset=['overview'], inplace=True)

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

## Creating Combined Features

To build a content-based recommendation system, we combine different movie attributes into a single text feature.

The combined feature includes movie overview, genres, keywords, cast, and director information.

This combined text will be used by the TF-IDF algorithm to understand similarities between movies.

In [ ]:
movies['tags'] = (
    movies['overview'] +
    movies['genres'] +
    movies['keywords'] +
    movies['cast'] +
    movies['director']
)

In [ ]:
movies[['tags']].head()

                                                tags
0  [In, the, 22nd, century,, a, paraplegic, Marin...
1  [Captain, Barbossa,, long, believed, to, be, d...
2  [A, cryptic, message, from, Bond’s, past, send...
3  [Following, the, death, of, District, Attorney...
4  [John, Carter, is, a, war-weary,, former, mili...

In [ ]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [ ]:
movies['tags'] = movies['tags'].apply(lambda x:x.lower())

In [ ]:
movies[['title','tags']].head()

,title,tags
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,Spectre,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,"john carter is a war-weary, former military ca..."

**Raw Dataset
      >
Data Cleaning
      >
Extract Genres
      >
Extract Keywords
      >
Extract Cast
      >
Extract Director
      >
Create Tags
      >
Ready for NLP Model**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
import numpy as np

similarity = similarity.astype(np.float32)

print(similarity.dtype)

float32

In [ ]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

In [ ]:
vectors = tfidf.fit_transform(movies['tags'])

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(vectors)

In [ ]:
similarity.shape

(4806, 4806)

In [ ]:
print(similarity.dtype)

float64

In [ ]:
def recommend(movie):

    # Find selected movie index
    index = movies[movies['title'] == movie].index[0]

    # Get similarity scores of selected movie
    distances = similarity[index]

    # Sort movies based on similarity score
    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:6]


    recommendations = []

    for i in movies_list:
        recommendations.append({
            "title": movies.iloc[i[0]].title,
            "similarity_score": round(i[1], 2)
        })

    return recommendations

In [ ]:
recommend('Avatar')

[{'title': 'Aliens', 'similarity_score': np.float64(0.43)},
 {'title': 'Alien', 'similarity_score': np.float64(0.36)},
 {'title': 'Moonraker', 'similarity_score': np.float64(0.35)},
 {'title': 'Alien³', 'similarity_score': np.float64(0.35)},
 {'title': 'Silent Running', 'similarity_score': np.float64(0.32)}]

In [ ]:
import pickle

In [ ]:
pickle.dump(
    movies,
    open('movies.pkl','wb')
)

In [ ]:
pickle.dump(
    similarity,
    open("similarity.pkl", "wb")
)

In [ ]:
movies.columns

Index(['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast',
       'director', 'tags'],
      dtype='object')